### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by zakpaw** [gptscript-ai/go-gptscript#33]
Hi, whenever I try to run the script below I get the following error: 
`failed to wait for gptscript to be ready: context deadline exceeded`

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/gptscript-ai/go-gptscript"
)

func listModels(ctx context.Context) ([]string, error) {
	g, err := gptscript.NewGPTScript(gptscript.GlobalOptions{OpenAIAPIKey: os.Getenv("OPENAI_API_KEY")})
	if err != nil {
		panic(fmt.Sprintf("error creating gptscript: %s", err))
	}
	defer g.Close()
	return g.ListModels(ctx)
}

func main() {
	ctx := context.Background()
	fmt.Println(listModels(ctx))
}
```

**Comment by thedadams** [comment]
@zakpaw Thanks for your report.

Do you have the `gptscript` CLI on your path? Otherwise, you can set the `GPTSCRIPT_BIN` environment variable to point at the `gptscript` CLI.

**Comment by zakpaw** [comment]
I do, Its a full path to gptscript installed with devbox (nix)

**Comment by thedadams** [comment]
OK, awesome! Which version of gptscript are you using?

**Comment by zakpaw** [comment]
gptscript version v0.5.0
go mod github.com/gptscript-ai/go-gptscript v0.0.0-20240613214812-8111c2b02d71

**Comment by thedadams** [comment]
OK, thanks for that information!

I see the issue: your version of the `gptscript` CLI is out of date. Can you try using the latest version (`v0.8.3`)?

**Comment by zakpaw** [comment]
Ah I see, 0.5.0 is the latest available in nixpkgs. I'll update and give it a try. Thanks!
